import { getShell } from './shell.ts';

const help = [
  'Cleverly converts markdown files into mocha cli tests',
  '',
  'USAGE',
  '  $ leia <files> <patterns> [--cleanup-header=<cleanup-headers>] [--debug] ',
  '  [--help] [--ignore=<patterns>] [--module-format=<auto|commonjs|esm>] ',
  '  [--retry=<count>] [--setup-header=<setup-headers>] ',
  '  [--test-header=<test-headers>] [--shell=<bash|cmd|powershell|pwsh|sh|zsh>] ',
  '  [--stdin] [--timeout=<seconds>] [--version]',
  '',
  'ARGUMENTS',
  '  TESTS  files or patterns to scan for test',
  '',
  'OPTIONS',
  '  -c, --cleanup-header=cleanup-header      [default: Clean,Tear,Burn] considers',
  '                                           these h2 sections as cleanup commands',
  '',
  '  -i, --ignore=ignore                      files or patterns to ignore',
  '',
  '  -r, --retry=retry                        [default: 1] non-negative number of',
  '                                           times to retry each test',
  '',
  '  -s, --setup-header=setup-header          [default: Start,Setup,This is the',
  '                                           dawning] considers these h2 sections',
  '                                           as setup commands',
  '',
  '  -t, --test-header=test-header            [default: Test,Validat,Verif]',
  '                                           considers these h2 sections as tests',
  '',
  '  -v, --version                            shows version info',
  '',
  '  --debug                                  shows debug output',
  '',
  '  --help                                   shows help',
  '',
  '  --module-format=auto|commonjs|esm        [default: auto] generates CommonJS or',
  '                                           ESM harnesses, autodetected by',
  '                                           default',
  '',
  '  --shell=bash|cmd|powershell|pwsh|sh|zsh  [default: {shell}] runs tests with',
  '                                           given shell, autodetected by default',
  '',
  '  --stdin                                  attachs stdin when the test is run',
  '',
  '  --timeout=timeout                        [default: 1800] non-negative whole',
  '                                           seconds before tests time out (max',
  '                                           2147483)',
  '',
  'EXAMPLES',
  '  leia README.md',
  '  leia README.md "examples/**/*.md" --retry 6 --test-header Tizzestin',
  '  leia "examples/*.md" --ignore BUTNOTYOU.md test --stdin --timeout 5',
  '  leia README.md --shell cmd',
  '  leia README.md --module-format esm',
  '',
  '',
].join('\n');

export const helpText = (): string => help.replace('{shell}', getShell().binary);
