name: Run Compatibility Baseline

on:
  pull_request:

jobs:
  baseline-tests:
    runs-on: ubuntu-24.04
    env:
      TERM: xterm

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install Node from .node-version
        uses: actions/setup-node@v7
        with:
          node-version-file: '.node-version'
          cache: npm
      - name: Install dependencies
        run: npm clean-install --prefer-offline --frozen-lockfile

      - name: Run compatibility baseline
        run: npm run test:baseline
