name: Run Leia Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - macos-10.15
          - ubuntu-20.04
          - windows-2019
        node-version:
          - '14'
        shell:
          - bash
        include:
          - os: macos-10.15
            shell: sh
          - os: ubuntu-20.04
            shell: sh
          - os: windows-2019
            shell: cmd

    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # Run Basic tests
      - name: Run Leia tests
        shell: ${{ matrix.shell }}
        run: yarn leia "examples/**/*.md" -i "examples/exclude-example/**/*.md" -i "examples/stdin-example.md" --debug


