name: Run Leia Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - ubuntu-22.04
          - windows-2022
        node-version:
          - '18'

    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm clean-install --prefer-offline --frozen-lockfile

      # Run a few iterations of leia tests
      - name: Run Leia tests
        shell: bash
        run: |
          # Try a basic example
          npx leia examples/basic-example.md --debug
          # Try globs and ignores
          npx leia "examples/**/*.md" -i "examples/basic-cmd-example.md" -i "examples/exclude-example/**/*.md" -i "examples/stdin-example.md" -i "examples/custom-headers.md" -i "examples/environment.md" -i "examples/basic-pwsh-example.md"
          # Try custom headers
          npx leia examples/custom-headers.md -s Hello -t Sup -c Goodbye
          # Try all other options, including legacy ones
          npx leia examples/basic-example.md --retry 2 --split-file --stdin --spawn
          # Try a comma separated list of headers
          npx leia examples/custom-headers.md -s Blue,No,Yellow,Hello -t Sup -c Goodbye
          # Assess envvars
          npx leia examples/environment.md examples/basic-example.md --retry 4 --timeout 5 --debug
