name: Run Shell Tests

on:
  pull_request:

jobs:
  shell-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - ubuntu-22.04
          - windows-2022
        node-version:
          - '18'

    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm clean-install --prefer-offline --frozen-lockfile

      # Run a few iterations of leia tests
      - name: Test macOS shells from
        if: ${{ runner.os == 'macOS' }}
        run: |
          npx leia examples/basic-example.md --debug
          npx leia examples/basic-example.md --shell bash --debug
          npx leia examples/basic-example.md --shell zsh --debug
          npx leia examples/basic-example.md --shell sh --debug
      - name: Test Linux shells
        if: ${{ runner.os == 'Linux' }}
        run: |
          npx leia examples/basic-example.md --debug
          npx leia examples/basic-example.md --shell bash --debug
          npx leia examples/basic-example.md --shell sh --debug
      - name: Test Windows BASH
        if: ${{ runner.os == 'Windows' }}
        shell: bash
        run: npx leia examples/basic-example.md --debug
      - name: Test Windows CMD
        if: ${{ runner.os == 'Windows' }}
        run: npx leia examples/basic-cmd-example.md --debug
