name: Run Unit Tests

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - macos-12
          - ubuntu-22.04
          - windows-2022
        node-version:
          - '16'
    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # Run unit tests
      - name: Run units tests
        run: yarn test:unit
